//! Diagnose the fixed PSD-reference knockout boundary matrix with the explicitly
//! selected compatibility profile. Expected pixels are never generated by Emulsion.
//! See tests/fixtures/psd/blending/README.md for provenance and strict scope limits.
#[path = "../tests/common/photoshop_blend_fixture.rs"]
mod photoshop;

use emulsion_raster::blend::BlendSpace;

fn main() -> anyhow::Result<()> {
    let space = BlendSpace::PhotoshopSrgbV1;
    println!(
        "Profile: photoshop-srgb-v1; inputs: numeric raw layers with explicit verified Background targets."
    );
    photoshop::verify_sources();
    let differences = photoshop::knockout_differences(space);
    if !differences.is_empty() {
        anyhow::bail!(
            "PSD-compatible sRGB v1 has unresolved independent knockout boundary mismatches:\n{}",
            differences.join("\n")
        );
    }
    println!("All four fixed 2026 PSD boundary references match exactly under photoshop-srgb-v1.");
    Ok(())
}
