[package]
name = "emulsion-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "GPUI views and design tokens for Emulsion"

[lints]
workspace = true

[dependencies]
emulsion-io = { workspace = true }
emulsion-raster = { workspace = true }
rayon = { workspace = true }
smallvec = { workspace = true }
image = { workspace = true }
parking_lot = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
gpui-kit = { workspace = true }
emulsion-core = { workspace = true }
