#!/usr/bin/env python3
"""Write THIRD_PARTY_CRATES.md: every crate in the dependency graph with its
declared licence, from `cargo metadata`. Run after changing dependencies."""
import json, subprocess, pathlib
meta = json.loads(subprocess.check_output(["cargo", "metadata", "--format-version", "1", "--locked"]))
ws = set(meta["workspace_members"])
rows = []
for p in meta["packages"]:
    if p["id"] in ws:
        continue
    src = p.get("source") or ""
    if "vendor/gpui" in (p.get("manifest_path") or "") or src == "":
        origin = "vendored" if "vendor/gpui" in (p.get("manifest_path") or "") else "path"
    else:
        origin = "crates.io" if "crates.io" in src else src
    rows.append((p["name"], p["version"], p.get("license") or "(see LICENSE in crate)", p.get("repository") or "", origin))
rows.sort(key=lambda r: (r[0].lower(), r[1]))
out = pathlib.Path("THIRD_PARTY_CRATES.md")
lines = ["# Third-party crates", "", "Generated by `scripts/gen-third-party.py` from `cargo metadata`; do not edit by hand.",
         f"{len(rows)} packages. Licences are as declared by each crate's `Cargo.toml`.", "",
         "| Crate | Version | Licence | Source |", "|---|---|---|---|"]
for n, v, l, r, o in rows:
    src = f"[{o}]({r})" if r else o
    lines.append(f"| {n} | {v} | {l} | {src} |")
out.write_text("\n".join(lines) + "\n")
print(f"{len(rows)} packages → {out}")
from collections import Counter
print(Counter(r[2] for r in rows).most_common(12))
