#!/usr/bin/env python3
"""Import the MIT-licensed peva3/Lightroom-Presets library into Emulsion.

Copies every XMP develop-settings (crs) `.xmp` preset into
`assets/develop-presets/film-library/<Category>/`, keeps the upstream license,
and regenerates `crates/emulsion-io/src/film_library_index.rs`, which embeds
each preset with its category and the upstream one-line description.

Usage: python3 scripts/sync-film-presets.py <checkout of peva3/Lightroom-Presets>
"""
import html
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEST = ROOT / "assets" / "develop-presets" / "film-library"
INDEX = ROOT / "crates" / "emulsion-io" / "src" / "film_library_index.rs"


def descriptions(docs: pathlib.Path) -> dict:
    """Preset name -> description from the upstream category tables."""
    out = {}
    row = re.compile(r"^\|\s*\d+\s*\|\s*\*\*(.+?)\*\*\s*\|\s*(.+?)\s*\|\s*$")
    for page in sorted(docs.glob("*.md")):
        for line in page.read_text(encoding="utf-8").splitlines():
            m = row.match(line)
            if m:
                text = re.sub(r"\*\*|`", "", m.group(2))
                text = re.sub(r"\s+", " ", text).strip()
                out.setdefault(m.group(1).strip().lower(), text[:300])
    return out


def preset_name(xmp: str, fallback: str) -> str:
    """Display name: XML entities decoded, upstream sort prefixes ("02 ") dropped."""
    m = re.search(r'crs:Name="([^"]+)"', xmp)
    name = html.unescape(m.group(1)) if m else fallback
    return re.sub(r"^\d{2}\s+", "", name).strip()


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src = pathlib.Path(sys.argv[1])
    presets = src / "Presets"
    if not presets.is_dir() or not (src / "LICENSE").is_file():
        sys.exit("Not a Lightroom-Presets checkout: missing Presets/ or LICENSE")
    commit = subprocess.run(
        ["git", "-C", str(src), "rev-parse", "HEAD"], capture_output=True, text=True
    ).stdout.strip() or "unknown"
    notes = descriptions(src / "docs")

    if DEST.exists():
        shutil.rmtree(DEST)
    DEST.mkdir(parents=True)
    shutil.copy(src / "LICENSE", DEST / "LICENSE")
    (DEST / "SOURCE.md").write_text(
        "# Film preset library\n\n"
        "XMP develop-settings (crs) `.xmp` presets from "
        "[peva3/Lightroom-Presets](https://github.com/peva3/Lightroom-Presets), "
        f"commit `{commit}`, MIT License (see `LICENSE`).\n\n"
        "Copied unmodified by `scripts/sync-film-presets.py`, which also generates "
        "`crates/emulsion-io/src/film_library_index.rs`. Emulsion translates them "
        "to its own renderer; the appearance can differ from the original application.\n",
        encoding="utf-8",
    )

    entries = []
    seen = set()
    for path in sorted(presets.rglob("*.xmp")):
        category = path.parent.relative_to(presets).as_posix()
        xmp = path.read_text(encoding="utf-8")
        name = preset_name(xmp, path.stem)
        if name.lower() in seen:
            continue
        seen.add(name.lower())
        target = DEST / category / path.name
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(path, target)
        rel = target.relative_to(ROOT).as_posix()
        entries.append(
            "    FilmPreset {\n"
            f"        category: {rust_str(category)},\n"
            f"        name: {rust_str(name)},\n"
            f"        description: {rust_str(notes.get(name.lower(), notes.get(path.stem.lower(), '')))},\n"
            f"        xmp: include_str!(\"../../../{rel}\"),\n"
            "    },\n"
        )

    INDEX.write_text(
        "// @generated by scripts/sync-film-presets.py from peva3/Lightroom-Presets\n"
        f"// commit {commit} (MIT License, assets/develop-presets/film-library/LICENSE).\n"
        "// Do not edit by hand; rerun the script to update.\n"
        "use super::FilmPreset;\n\n"
        "pub(super) const PRESETS: &[FilmPreset] = &[\n" + "".join(entries) + "];\n",
        encoding="utf-8",
    )
    print(f"{len(entries)} presets from {commit}")


if __name__ == "__main__":
    main()
