[package]
name = "emulsion-ai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Optional local AI"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
emulsion-raster = { workspace = true }
emulsion-core = { workspace = true }
ureq = { workspace = true }
