//! The community recipe library shipped with Emulsion: film recipes shared
//! by Fujifilm photographers, grouped into one collection per film
//! simulation family. The bundles under `library/` are generated by
//! `scripts/gen-recipe-library.js` from Open Fuji Recipes and the
//! akirichev/fujifilm-recipes X RAW Studio profiles; each recipe keeps its
//! creator and source.

use crate::Recipe;
use crate::bundle::Bundle;
use std::sync::OnceLock;

/// A named group of recipes, in the order the panel shows them.
pub struct Collection {
    pub name: String,
    pub notes: String,
    pub recipes: Vec<Recipe>,
}

/// The bundle files, in menu order.
const BUNDLES: &[&str] = &[
    include_str!("../library/classic-chrome.toml"),
    include_str!("../library/classic-negative.toml"),
    include_str!("../library/provia.toml"),
    include_str!("../library/velvia.toml"),
    include_str!("../library/astia.toml"),
    include_str!("../library/pro-neg.toml"),
    include_str!("../library/eterna.toml"),
    include_str!("../library/monochrome.toml"),
];

/// Every collection, parsed once. A bundle that fails to parse is a build
/// defect, so it panics in debug builds and is skipped in release builds.
pub fn collections() -> &'static [Collection] {
    static ALL: OnceLock<Vec<Collection>> = OnceLock::new();
    ALL.get_or_init(|| {
        BUNDLES
            .iter()
            .filter_map(|text| match Bundle::from_toml(text) {
                Ok(b) => Some(Collection {
                    name: b.name,
                    notes: b.notes,
                    recipes: b.recipes,
                }),
                Err(e) => {
                    debug_assert!(false, "library bundle: {e}");
                    None
                }
            })
            .collect()
    })
}

/// Every library recipe with the name of its collection.
pub fn recipes() -> impl Iterator<Item = (&'static Recipe, &'static str)> {
    collections()
        .iter()
        .flat_map(|c| c.recipes.iter().map(move |r| (r, c.name.as_str())))
}

/// The collection a library recipe belongs to, by recipe name.
pub fn collection_of(name: &str) -> Option<&'static str> {
    recipes()
        .find(|(r, _)| r.name.eq_ignore_ascii_case(name))
        .map(|(_, c)| c)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{cameras, looks, starter_set};
    use std::collections::HashSet;

    #[test]
    fn every_bundle_parses_into_a_named_collection() {
        let all = collections();
        assert_eq!(all.len(), BUNDLES.len(), "every bundle parsed");
        for c in all {
            assert!(!c.name.is_empty() && !c.notes.is_empty());
            assert!(!c.recipes.is_empty(), "{} has recipes", c.name);
        }
        assert!(recipes().count() >= 200, "the whole community set is in");
    }

    #[test]
    fn names_are_unique_across_built_in_sets_and_the_library() {
        let mut seen: HashSet<String> = HashSet::new();
        for r in starter_set().iter().chain(cameras::presets().iter()) {
            assert!(seen.insert(r.name.to_lowercase()), "{}", r.name);
        }
        for (r, c) in recipes() {
            assert!(seen.insert(r.name.to_lowercase()), "{} in {c}", r.name);
        }
        assert_eq!(
            collection_of("kodachrome 64 · x raw studio"),
            Some("Classic Chrome")
        );
        assert_eq!(collection_of("Chrome Street"), None);
    }

    #[test]
    fn every_library_recipe_is_attributed_and_compiles() {
        for (r, c) in recipes() {
            r.validate()
                .unwrap_or_else(|e| panic!("{} in {c}: {e}", r.name));
            assert!(
                !r.author.is_empty() && !r.source_url.is_empty(),
                "{}",
                r.name
            );
            assert!(!r.sensor.is_empty() && r.tags.len() >= 3, "{}", r.name);
            let look = looks::find(&r.film_simulation).expect(&r.name);
            assert!(
                r.tags.contains(&look.key.to_string()),
                "{} tagged by look",
                r.name
            );
            let (_, stages) = r.compile(None);
            assert!(!stages.is_empty(), "{}", r.name);
        }
        // Grouping follows the base look.
        for c in collections() {
            for r in &c.recipes {
                let sim = r.film_simulation.as_str();
                let ok = match c.name.as_str() {
                    "Black and white" => {
                        sim.starts_with("acros") || sim.starts_with("monochrome") || sim == "sepia"
                    }
                    "Pro Neg" => sim.starts_with("pro-neg"),
                    "Eterna" => sim.starts_with("eterna"),
                    name => looks::find(sim)
                        .is_some_and(|l| l.key == name.to_lowercase().replace(' ', "-")),
                };
                assert!(ok, "{} ({sim}) belongs in {}", r.name, c.name);
            }
        }
    }
}
