[package]
name = "emulsion-recipes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Recipes"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
emulsion-filters = { workspace = true }
emulsion-color = { workspace = true }
